---
logging:
  level:
    root: WARN
    org:
      springframework:
        # web: DEBUG
        security: DEBUG
---
server:
  port: ${PORT:7070}
---
base-url: /api
---
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always
  h2:
    console.enabled: true
  liquibase:
    change-log: ../db.changelog-master.yaml

---
springdoc:
  swagger-ui:
    path: /swagger
---
server:
  address: 0.0.0.0